### ISSUE TITLE
Can't create site

### ISSUE THREAD

**Issue by LestaD** [rynclark/hay#14]
![image](https://cloud.githubusercontent.com/assets/5620073/20726816/26142c90-b688-11e6-8988-708575e5d24e.png)

**Comment by rynclark** [comment]
Hey - this hasn't been released yet! First release is coming very shortly :)

**Comment by LestaD** [comment]
@rynclark can i help you?

**Comment by rynclark** [comment]
@LestaD once I've got the first release out I'm sure there will be lots more to add!

**Comment by LestaD** [comment]
@rynclark maybe create github organization for hay?
Move project's repo and site's repo

**Comment by rynclark** [comment]
@LestaD created the org @hayjs

**Comment by LestaD** [comment]
@rynclark will u move general repo to @hayjs?

**Comment by rynclark** [comment]
@LestaD done
